- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes

- name: Install Gitlab apt dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ gitlab_server_omnibus_ubuntu_dependencies }}"

- name: Start runit service
  ansible.builtin.service:
    name: runit
    state: started
    enabled: yes

- name: Download Gitlab package repository install script
  ansible.builtin.uri:
    url: "{{ gitlab_server_omnibus_ubuntu_install_script_url }}"
    dest: "{{ gitlab_server_omnibus_ubuntu_install_script_path }}"
    mode: "0755"

- name: Install Gitlab package repository using provided script
  ansible.builtin.command: bash "{{ gitlab_server_omnibus_ubuntu_install_script_path }}"

- name: Install Gitlab package
  ansible.builtin.apt:
    name: gitlab-ee
    state: present

- name: Replace external_url with a dynamic URL in gitlab.rb
  ansible.builtin.replace:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url\\s+'.*'"
    replace: "external_url '{{ gitlab_server_external_url }}'"

- name: Stop GitLab
  ansible.builtin.command: gitlab-ctl stop

- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure

- name: Start GitLab
  ansible.builtin.command: gitlab-ctl start
