
Vagrant.configure("2") do |config| 
    config.vm.box = "generic/ubuntu2204"
    config.vm.define "dev" do |dev|
      dev.vm.network "public_network", dev: "enp0s31f6"
      dev.vm.provider :libvirt do |libvirt|
        libvirt.driver = 'kvm'
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.memory = 1024
        libvirt.cpus = 1
        libvirt.storage :file, size: '5G'
      end
      dev.vm.provision :ansible do |ansible|
        ansible.playbook = "test.yml"
      end
    end
end
