# We create a Vagrantfile to test the role 
# The VM is a ubuntu 20.04 server on KVM with libvirt 
# It will have Docker installed with "docker-admin" user in docker group
#

Vagrant.configure("2") do |config| 

config.vm.box = "generic/ubuntu2204" # Ubuntu 20.04 LTS

config.vm.define "docker" do |docker|
  docker.vm.network "public_network", dev: "enp0s31f6"
  docker.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.memory = 1024
    libvirt.cpus = 1
    libvirt.storage :file, size: '5G'
  docker.vm.provision :ansible do |ansible| 
    ansible.playbook = "test.yml"
  end 
  end
end
end
