---
# Main tasks for the kvm_host role

- name: Install KVM on Ubuntu Host
  # Include tasks specific to Ubuntu systems
  include_tasks: ubuntu.yml
  # Execute only if the target system is running Ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Create "libvirt" group
  ansible.builtin.group:
    name: libvirt
    state: present

- name: Create "kvm" group
  ansible.builtin.group:
    name: kvm
    state: present

- name: Add "libvirt" group to users in "kvm_host_libvirt_users" list
  ansible.builtin.user:
    name: "{{ item }}"
    groups: libvirt
    append: true
  loop: "{{ kvm_host_libvirt_users }}"

- name: Add "kvm" group to users in "kvm_host_libvirt_users" list
  ansible.builtin.user:
    name: "{{ item }}"
    groups: kvm
    append: true
  loop: "{{ kvm_host_libvirt_users }}"
