# install apt package
- name: Install necessary packages
  apt:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
    state: present
